#!/usr/bin/env bash
# designed to pings an IP address passed as an argument

# introducing ip variable
IP="${1}"

# introducing filename variable
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
