#!/usr/bin/env bash
# Displays Fizzbuzz task

l=1

while [ "$l" -le 100 ]; do


  if ! (( l % 3 )) && ! (( l % 5 )); then
    echo "FizzBuzz"
  elif ! (( l % 3 )); then
    echo "Fizz"
  elif ! (( l % 5 )); then
    echo "Buzz"
  else
    echo "$l"
  fi
  
  ((l++))
done
