#!/usr/bin/env bash
# Showcase Best School 10 times and on 9th it prints hi

g=1

while [ "$g" -lt 11 ]; do
  echo "Best School"
  
  # display 9 when g = 9
  if [ "$g" -eq 9 ]; then
    echo "Hi"
  fi

  ((g++))
done
