#!/usr/bin/env bash
# Showcase good luck and bad luck

q=1

while [ "$q" -lt 11 ]; do

  # elif 9th
  if [ "$q" -eq 4 ]; then
    echo "bad luck"
  elif [ "$q" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((q++))
done
