#!/usr/bin/env bash
# making number

w=1

while [ "$w" -lt 21 ]; do
  
  case "$w" in
    4)
      echo "$w"
      echo "bad luck from China"
      ;;
    9)
      echo "$w"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$w"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$w"
      ;;
  esac

  ((w++))
done
