#!/usr/bin/env bash
# checker alx file

file="school"

# ascertain file existency
if [ -e "$file" ]; then

  echo "school file exists"

  # knowing if file is empty
  if [ ! -s "$file" ]; then
    echo "school file is empty"

    # knows if a file is a regular file
    if [ -f "$file" ]; then
      echo "school is a regular file"
    fi  

  else

    echo "school file is not empty"

    # knows if file is a regular file
    if [ -f "$file" ]; then
      echo "school is a regular file"
    fi  
  
  fi

else
  
  echo "school file does not exist"

fi
